import json
import Connectors
import Transformations
import AutoML
try:
    MeterAnomaly_DBFS = Connectors.DBFSConnector.fetch(
        [], {}, "5e9981b46b53f44d6a646b39", spark, "{'url': '/Demo/MeterAnomalyTrain.csv', 'file_type': 'Delimeted', 'dbfs_token': 'dapib8073bbfa952efa9d363b234ce06e2c6', 'dbfs_domain': 'westus.azuredatabricks.net', 'delimiter': ',', 'is_header': 'Use Header Line'}")

except Exception as ex:
    print(ex)
try:
    MeterAnomaly_AutoFE = Transformations.TransformationMain.run(["5e9981b46b53f44d6a646b39"], {"5e9981b46b53f44d6a646b39": MeterAnomaly_DBFS}, "5e9981b46b53f44d6a646b3a", spark, json.dumps({"FE": [{"transformationsData": {"feature_label": "BADGE_NBR"}, "feature": "BADGE_NBR", "type": "string", "selected": "True", "replaceby": "max", "stats": {"count": "88656", "mean": "", "stddev": "", "min": "M00006224", "max": "M02590464", "missing": "0"}, "transformation": "String Indexer"}, {"transformationsData": {}, "feature": "INT_SUM_DAY_USG", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "88656", "mean": "156.93", "stddev": "81.96", "min": "0.0", "max": "982.8", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "MONTH_AVG_USG", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "88656", "mean": "190.56", "stddev": "112.89", "min": "0.0", "max": "979.46", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "HIGHEST_INT_DAY_USG", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "88656", "mean": "11.11", "stddev": "5.0", "min": "0.0", "max": "46.33", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "METER_TYPE", "transformation": "", "type": "numeric", "replaceby": "mean", "selected": "True", "stats": {"count": "88656", "mean": "60.0", "stddev": "0.0", "min": "60", "max": "60", "missing": "0"}}, {"transformationsData": {"feature_label": "WEEK_DAY_IND"}, "feature": "WEEK_DAY_IND", "type": "string", "selected": "True", "replaceby": "max", "stats": {"count": "88656", "mean": "", "stddev": "", "min": "N", "max": "Y", "missing": "0"}, "transformation": "String Indexer"}, {"transformationsData": {"feature_label": "MONTH_NM"}, "feature": "MONTH_NM", "type": "string", "selected": "True", "replaceby": "max", "stats": {"count": "88656", "mean": "", "stddev": "", "min": "FEBRUARY ", "max": "MARCH    ", "missing": "0"}, "transformation": "String Indexer"}, {"transformationsData": {}, "feature": "DAILY_AVG_TEMP", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "88656", "mean": "58.16", "stddev": "8.45", "min": "40.5", "max": "74.0", "missing": "0"}, "transformation": ""}, {"transformationsData": {"feature_label": "CITY"}, "feature": "CITY", "type": "string", "selected": "True", "replaceby": "max", "stats": {"count": "88656", "mean": "", "stddev": "", "min": "AGUILA", "max": "YUMA", "missing": "0"}, "transformation": "String Indexer"}, {
                                                                 "transformationsData": {"feature_label": "MFG_CD"}, "feature": "MFG_CD", "type": "string", "selected": "True", "replaceby": "max", "stats": {"count": "88656", "mean": "", "stddev": "", "min": "ELSTER", "max": "LG", "missing": "0"}, "transformation": "String Indexer"}, {"transformationsData": {"feature_label": "SP_TYPE_CD"}, "feature": "SP_TYPE_CD", "type": "string", "selected": "True", "replaceby": "max", "stats": {"count": "88656", "mean": "", "stddev": "", "min": "COMM", "max": "RES", "missing": "0"}, "transformation": "String Indexer"}, {"transformationsData": {}, "feature": "USAGE_VAR_PER", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "88656", "mean": "-379.72", "stddev": "16218.13", "min": "-2617800.0", "max": "91.86", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "ISSUE_IND", "transformation": "", "type": "numeric", "replaceby": "mean", "selected": "True", "stats": {"count": "88656", "mean": "0.36", "stddev": "0.48", "min": "0", "max": "1", "missing": "0"}}, {"feature": "BADGE_NBR_transform", "transformation": "", "transformationsData": {}, "type": "real", "selected": "True", "stats": {"count": "88656", "mean": "882.77", "stddev": "653.49", "min": "0.0", "max": "2233.0", "missing": "0"}}, {"feature": "WEEK_DAY_IND_transform", "transformation": "", "transformationsData": {}, "type": "numeric", "selected": "True", "stats": {"count": "88656", "mean": "0.29", "stddev": "0.46", "min": "0", "max": "1", "missing": "0"}}, {"feature": "MONTH_NM_transform", "transformation": "", "transformationsData": {}, "type": "numeric", "selected": "True", "stats": {"count": "88656", "mean": "0.86", "stddev": "0.8", "min": "0", "max": "2", "missing": "0"}}, {"feature": "CITY_transform", "transformation": "", "transformationsData": {}, "type": "real", "selected": "True", "stats": {"count": "88656", "mean": "8.85", "stddev": "14.22", "min": "0.0", "max": "92.0", "missing": "0"}}, {"feature": "MFG_CD_transform", "transformation": "", "transformationsData": {}, "type": "numeric", "selected": "True", "stats": {"count": "88656", "mean": "0.07", "stddev": "0.25", "min": "0", "max": "1", "missing": "0"}}, {"feature": "SP_TYPE_CD_transform", "transformation": "", "transformationsData": {}, "type": "numeric", "selected": "True", "stats": {"count": "88656", "mean": "0.01", "stddev": "0.09", "min": "0", "max": "3", "missing": "0"}}]}))

except Exception as ex:
    print(ex)
try:
    AutoML.functionClassification(MeterAnomaly_AutoFE, ["BADGE_NBR", "INT_SUM_DAY_USG", "MONTH_AVG_USG", "HIGHEST_INT_DAY_USG",
                                                        "METER_TYPE", "WEEK_DAY_IND", "MONTH_NM", "DAILY_AVG_TEMP", "CITY", "MFG_CD", "SP_TYPE_CD", "USAGE_VAR_PER"], "ISSUE_IND")

except Exception as ex:
    print(ex)
